# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('uo', models.CharField(max_length=120, verbose_name='Campus')),
            ],
            options={
                'verbose_name': 'Biblioteca',
                'verbose_name_plural': 'Bibliotecas',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('data_prevista_devolucao', models.DateField(verbose_name='Data Prevista para a Devolu\xe7\xe3o')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Empr\xe9stimo',
                'verbose_name_plural': 'Empr\xe9stimos',
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisi\xe7\xe3o')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Biblioteca', verbose_name='Biblioteca')),
            ],
            options={
                'verbose_name': 'Exemplar',
                'verbose_name_plural': 'Exemplares',
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('username', models.CharField(max_length=120, verbose_name='Nome de Usu\xe1rio')),
            ],
            options={
                'verbose_name': 'Pessoa F\xedsica',
                'verbose_name_plural': 'Pessoas F\xedsicas',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('categoria', models.CharField(max_length=60, verbose_name='Categoria')),
                ('imagem', models.ImageField(upload_to=b'', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'T\xedtulo',
                'verbose_name_plural': 'T\xedtulos',
            },
        ),
        migrations.AddField(
            model_name='exemplar',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Titulo', verbose_name='T\xedtulo'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='exemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Exemplar'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usu\xe1rio'),
        ),
    ]
