# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True, verbose_name='Data do Empr\xe9stimo')),
                ('data_prevista_devolucao', models.DateField(blank=True, null=True, verbose_name='Data Prevista para Devolu\xe7\xe3o')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data da Devolu\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'Pessoa F\xedsica',
                'verbose_name_plural': 'Pessoas F\xedsicas',
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aquisicao', models.DateField(auto_now_add=True, verbose_name='Data da Aquisi\xe7\xe3o')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Biblioteca', verbose_name='Biblioteca')),
            ],
            options={
                'verbose_name': 'T\xedtulo',
                'verbose_name_plural': 'T\xedtulos',
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('username', models.CharField(max_length=120, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Pessoa F\xedsica',
                'verbose_name_plural': 'Pessoas F\xedsicas',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('imagem', models.ImageField(upload_to='uploads/imagens/', verbose_name='Imagem')),
                ('categorias', models.ManyToManyField(to='biblioteca.Categoria', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'T\xedtulo',
                'verbose_name_plural': 'T\xedtulos',
            },
        ),
        migrations.AddField(
            model_name='exemplar',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Titulo', verbose_name='T\xedtulo'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='exemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Exemplar', verbose_name='Exemplar'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.PessoaFisica', verbose_name='Usu\xe1rio'),
        ),
    ]
