# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20180926_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name': 'Empr\xe9stimo', 'verbose_name_plural': 'Empr\xe9stimos'},
        ),
        migrations.AlterModelOptions(
            name='exemplar',
            options={'verbose_name': 'Exemplar', 'verbose_name_plural': 'Exemplares'},
        ),
        migrations.AlterField(
            model_name='campus',
            name='nome',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='data_aquisicao',
            field=models.DateField(verbose_name='Data da Aquisi\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='username',
            field=models.CharField(max_length=120, verbose_name='Nome de Usu\xe1rio'),
        ),
    ]
