# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20180926_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='capitulo_exemplo',
            field=models.FileField(null=True, upload_to='static/uploads/pdfs/', verbose_name='Cap\xedtulo de Exemplo'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='imagem',
            field=models.ImageField(upload_to='static/uploads/imagens/', verbose_name='Imagem'),
        ),
    ]
