# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20180926_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
